### ISSUE TITLE
Consider adding more topics to the repository

### ISSUE THREAD

**Issue by php-coder** [qala-io/datagen#13]
At this time, there are only 3 topics (java, testing, randomization). Consider adding more topics to allow github users to discover this repo. For example:
- [random-number-generators](https://github.com/topics/random-number-generators)
- [random-data-generation](https://github.com/topics/random-data-generation)
- [random-generation](https://github.com/topics/random-generation)
- [random](https://github.com/topics/random)

**Comment by ctapobep** [comment]
Done, thanks!
