### ISSUE TITLE
sampleMultiple() to never return empty list

### ISSUE THREAD

**Issue by ctapobep** [qala-io/datagen#14]
Returning empty list may be a rare use case for such a method. So might be worth reworking it to return 1-N elements.

**Comment by php-coder** [comment]
Would it be possible to write something like this?
```java
List<Foo> foos = emptyOr(sampleMultiple(...));
```
?

**Comment by ctapobep** [comment]
Yes, this looks like a clean way.

**Comment by ctapobep** [comment]
`sampleMultiple()` is fixed since 2.3.0, though `emptyOr()` wasn't added for collections yet.
