### ISSUE TITLE
Provide a way of generating a list of values with specific characteristics

### ISSUE THREAD

**Issue by php-coder** [qala-io/datagen#18]
We have many methods for generating just a single value but it would be super useful to provide an API for generating a list (or set) of value with some characteristics.

Maybe something like this:
```java
List<Integer> ints = RandomList.ofLength(between(1, 5)).withValues(between(1, 10));
```

Another option is to leverage Java 8 streams API and have a method that takes a function that produce some value and invokes this function `N` times.

**Comment by ctapobep** [comment]
The API that you're looking for may already exist:

```java
length(5).alphanumerics(500)
```

**Comment by php-coder** [comment]
Ok, thanks! I'll try to use it but it still doesn't cover the case when I have a custom object generator.

**Comment by php-coder** [comment]
I've just tried to refactor some my helpers and I gave up. Because my understanding how it should be didn't work with the library API at least once, now I can't fully trust it. Also I can't read about these methods because there is no API docs.

For example, I found that there is `numerics()` method but I don't know what it does. Instead of having frustration with API each time, I started to think that it's better to write my own random generators.. :-(

**Comment by ctapobep** [comment]
> I found that there is numerics() method but I don't know what it does.

I thought the API for this particular method was pretty straightforward:

```
> between(4, 6).with(spacesLeft(2)).numerics(3)
"  8467", "  231", "  72"
```

Is there something confusing?

> I started to think that it's better to write my own random generators

That's perfectly fine. There won't be any library that satisfies _all_ your needs. Datagen could be used to either for widespread cases or to help you build your own randomization utilities.

> Also I can't read about these methods because there is no API docs.

JavaDocs will be added with time. I agree that this should be done, I just don't have much time/inspiration to work on the lib right now. But do you need JavaDocs _that_ badly? Most of the methods in the lib are 1-5 lines long. Even for those that have JavaDocs it could be easier to read source code.
