### ISSUE TITLE
StringModifier: provide a modifier for changing the case of a string

### ISSUE THREAD

**Issue by php-coder** [qala-io/datagen#20]
It would be good to have modifiers that convert a string to lower/upper case. At this moment, it has to be written by user and it's not just a one liner because of #19

**Comment by ctapobep** [comment]
Why don't you change the case after randomization? E.g. `english(10).toUpperCase()`?

**Comment by php-coder** [comment]
I've already done that but had idea that maybe it should be done on the library side.

**Comment by ctapobep** [comment]
Nah.. Unless pure Java is too cumbersome it should have higher priority than custom API.
