### ISSUE TITLE
Add quick start examples

### ISSUE THREAD

**Issue by ctapobep** [qala-io/datagen#4]
From @php-coder:

> I'm trying to use this library and I'm missing a good quick start with examples.

**Comment by ctapobep** [comment]
So the examples are supposed to be in the main README. I thought that those were enough. I can add more, but would be great if you could give me a hint about what kind of docs you're missing.

**Comment by php-coder** [comment]
> So the examples are supposed to be in the main README.

In my opinion, README _could_ have a couple examples but it should not be a replacement for documentation.

The biggest confusing moment to me was that I couldn't parse them. They look like a code but they aren't a real code and in some cases it's not clear where is the code and where is just a word. Let's look at the following example:
```
import static io.qala.datagen.RandomShortApi.*;

bool() or weighedTrue(0.5)
> false
```
There is `import` so it looks like a code. Now, the question is how to interpret `or` here? Is it logical operation? Where this code is being executed? It looks like an interpreter, maybe it's a groovy console (and in this case `or` could be part of DSL), or maybe it's a new REPL from Java 9 that I didn't try yet?

So, it should be a 100% code (with comments) or it should be a text. For example:
```java
import static io.qala.datagen.RandomShortApi.*;

// both will print true or false
System.out.println(bool());
System.out.println(weighedTrue(0.5));
```
or
```java
import static io.qala.datagen.RandomShortApi.*;

// both variables will have random boolean values
bool a = bool();
bool b = weighedTrue(0.5);
```

**Comment by php-coder** [comment]
BTW one of the reason of why I asked for API docs is that examples using stars in import that I don't won't to use. And in order to find out exact names, the API would be helpful.

**Comment by php-coder** [comment]
> I can add more, but would be great if you could give me a hint about what kind of docs you're missing.

I'd like to have a step-by-step guide with examples that is refactored to using this library. They should start from something pretty simple and introduce more methods. Perhaps it could be a 1-2 methods that has a code that will allow to demonstrate the methods from datagen.

It could be a method for registering user, that have a name, date of birth, phone number, home page, etc. Something like this.

**Comment by ctapobep** [comment]
Updated README. Does this look better? Or you still want something step-by-step?

> BTW one of the reason of why I asked for API docs is that examples using stars in import that I don't won't to use. And in order to find out exact names, the API would be helpful.

There are usually only one or two import statements, so you have only that many choices to take the methods from, right? I'm afraid if I add import statements to many more lines the docs will be more cluttered and harder to grasp.

**Comment by ctapobep** [comment]
I treat no answer as a positive answer :) Closing the ticket.
