### ISSUE TITLE
blankOr() that is returning null may confuse users

### ISSUE THREAD

**Issue by php-coder** [qala-io/datagen#6]
IMHO the behavior of `blankOr()` method is violating the [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

Maybe it's better to change it's behavior or rename a method.

**Comment by php-coder** [comment]
It was so confusing to me that I even prepared a PR for fixing the docs... :(

**Comment by ctapobep** [comment]
This terminology comes from Commons Lang and Bean Validation - they both use blank to denote empty string, null or spring with whitespaces. I think it's better to stick with something that people know from other projects and not invent yet another terminology.
