### ISSUE TITLE
Consider moving example of nullOr() to a dedicated section

### ISSUE THREAD

**Issue by php-coder** [qala-io/datagen#8]
Example of `nullOr("string")` that is returning `"string"` looks weird in Collections/Arrays section. My first impression was that it should be in the section about strings.

I suggest to
1) add example for `nullOr("string")` to the section about strings (for completeness)
2) remove this example from the Collections/Arrays section
3) introduce a dedicated section for `nullOr()` with different examples (to demonstrate that it uses generics and may accepts any types, not only strings)

**Comment by ctapobep** [comment]
Removed completely these examples in Strings and moved it all together into a new section. BTW, `nullOr()` doesn't necessarily work with Strings (added example for this too).

Thanks!
